### PR TITLE
Create Constructors for TickOptions

### PR DESCRIPTION
**Pull request by Verzu23**
Related Issue Abstract class error for "TickOptions" #33

Let me know if there something that could be done in different or in a better way

### CODE REVIEW

**Comment by Verzu23** [comment]
Submitted CLA

**Comment by Verzu23** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
Please undo your formatting here. There are a LOT of lines changed. I can't see what your actual, functional delta is!

**Comment by Verzu23** [comment]
Yes, sorry, for me it's working well now, just forgot to undo the formatting.....
Is possible to Sign a CLA with a no Google account? @kevmoo

**Comment by kevmoo** [comment]
I think you need a google account @Verzu23

**Pull request closed without merging**
