### PR TITLE
Rename toBase64() -> toBase64Image()

### PR DESCRIPTION
**Pull request by leerobinson-wf**
This function was not properly named and just returning `null` everytime. After switching `toBase64()` to `toBase64Image()`, I was able to confirm it worked locally.

```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABDYAAAFmCAYAAACWZRocAAAgAElEQ…AAAgggEC/Axka8FSURQAABBBBAAAEEEEAAAQQQQCAxgf8D9AtrCHr/qMUAAAAASUVORK5CYII=
```
@kevmoo

### CODE REVIEW

**Comment by leerobinson-wf** [comment]
@googlebot I signed it, thanks.

**Comment by kevmoo** [comment]
@leerobinson-wf which version of chartjs are you using?

Need to make sure we stay aligned here...

**Comment by leerobinson-wf** [comment]
@kevmoo I'm using version 0.3.1.

**Comment by leerobinson-wf** [comment]
@kevmoo Any update on this? Thanks

**Comment by kevmoo** [comment]
I already had some local changes pending.

Get me a sec to get them ready....

**Comment by leerobinson-wf** [comment]
@kevmoo Your latest commit didn't fix the issue. The function is still called `toBase64` and not `toBase64Image`.

**Comment by kevmoo** [comment]
Gah. The definitely typed thing is borked. Will reopen and pull in your fix.

Would you rebase?

Thanks!

**Comment by leerobinson-wf** [comment]
@kevmoo I forgot to mention you. This PR is ready again. Thanks!

**Review by kevmoo — APPROVED** [review]

**Pull request merged**
