### PR TITLE
Added type property in ChartDataSets to support mixed charts

### PR DESCRIPTION
**Pull request by portno**
Didn't find any other way to do it.

### CODE REVIEW

**Comment by portno** [comment]
I signed it!

**Comment by kevmoo** [comment]
Which version of chart.js was this introduced in?

**Comment by portno** [comment]
According to [this release](https://github.com/chartjs/Chart.js/releases/tag/v2.0.0) it was added in version 2.0.0, `Charts that combine visual types such as bars and lines`. Also, they mention mixed chart types in [their official website](http://www.chartjs.org/) as `New in 2.0`

**Comment by kevmoo** [comment]
I just pushed an update that should include chart.js 2.6

Please take a look at master and compare...

**Comment by portno** [comment]
The `type` property [exists](/google/chartjs.dart/blob/master/lib/chartjs.dart#L985). Please close this PR.

I've created another issue with feedback. #22

**Pull request closed without merging**
