### PR TITLE
Add some missing factory constructors.

### PR DESCRIPTION
**Pull request by ghost**
... by hand (not using "js facade gen").

For #26, but only added some of the missing, not fully covered.

### CODE REVIEW

**Comment by kevmoo** [comment]
@ntaoo – have you verified these work?

...makes me wish we had tests 😄

**Comment by ghost** [comment]
Yes. But only some parts of the options at my private repository, no test
code there, though.
If the test code base is set up. I would like to have time to add the test
code for this.

**Review by kevmoo — CHANGES_REQUESTED** [review]
Please update pubspec.yaml version to 0.5.1-dev

Please add an entry to the CHANGELOG under a new 0.5.1 header describing the change

**Comment by kevmoo** [comment]
@ntaoo – any updates?

**Comment by ghost** [comment]
@kevmoo Oh, very sorry. I updated now.

**Comment by supermuka** [comment]
There are more constructors missing as reported in https://github.com/google/chartjs.dart/issues/22

**Comment by wsv-accidis** [comment]
How about merging this for now? It would be very useful.

**Review by kevmoo — APPROVED** [review]

**Comment by wsv-accidis** [comment]
Hey thanks @kevmoo, that was fast. Dart's awesome, keep up the good work.

**Comment by oeztuerk** [comment]
@ntaoo 

I also had the same issue with those missing constructor as I wanted to use LinearTickOption to beginAtZero on bar charts. I fixed it by creating the missing constructor with it's attributes. See #33 . 
Would be grateful if you fix that on next package realease !

**Pull request merged**
