### PR TITLE
Added factory for ChartXAxe and ChartYAxe

### PR DESCRIPTION
**Pull request by zarisi**
Added missing factory for the classes ChartXAxe and ChartYAxe from the issue #26

Fixed error with author mail from PR #31

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
Have you validated that this works?

**Comment by zarisi** [comment]
I tried it in my code and it seems to work without problems

**Comment by basevers** [comment]
I'm guessing the same applies for "TickOptions".
Will create a separate issue for this.

**Comment by computmaxer** [comment]
@kevmoo could you publish a released with the latest factory constructor fixes? (Mainly interested in this and #29)

I would greatly appreciate it, thanks!

**Comment by computmaxer** [comment]
@kevmoo can we tag a release? Would love to remove the dependency_override for this package from my app 😄

**Comment by kevmoo** [comment]
Sorry for the lag here. Happy to tag and publish!

**Comment by kevmoo** [comment]
published as 0.5.1

**Comment by computmaxer** [comment]
Thanks Kevin!

**Pull request merged**
